name: Flask App CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        # Install from your requirements.txt
        if [ -f Question_paper_service/requirements.txt ]; then pip install -r Question_paper_service/requirements.txt; fi
    
    - name: Run basic syntax check
      run: |
        python -m py_compile Question_paper_service/app.py
    
    - name: Test Flask app imports
      run: |
        cd Question_paper_service
        python -c "from app import create_app; print('✓ Flask app imports successfully')"
    
    - name: Check directory structure
      run: |
        echo "Repository structure:"
        ls -la
        echo "Question_paper_service contents:"
        ls -la Question_paper_service/
